"""Prism FastAPI backend.

Run from repo root:
    .venv/bin/python3 -m uvicorn webapp.api.main:app --reload --port 8000

API docs available at http://localhost:8000/docs
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Ensure repo root is on sys.path so we can import utils.* / tools.* / agent.*
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from webapp.api.db import init_db
from webapp.api.routes import cost, digest, edges, knowledge, plans, prd, product_os, projects, reports, screens, xproj

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)

app = FastAPI(
    title="Prism API",
    description="Product intelligence platform — competitive research, trends, impacts. UAT lives in Loupe.",
    version="0.21.1",
)

# CORS — locals for dev, Vercel + is-a.dev for prod. Extra comma-separated
# origins can be set via CORS_ALLOW_ORIGINS env for ad-hoc previews.
import os as _os
_default_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    # v0.17.2: consolidated to a single canonical Vercel alias (prism-ros).
    # Old aliases — prism.is-a.dev (DNS broken), prism-intel (squatted by
    # another team), prism-three-alpha (autogenerated, replaced) — removed.
    "https://prism-ros.vercel.app",
]
_extra_origins = [o.strip() for o in (_os.environ.get("CORS_ALLOW_ORIGINS") or "").split(",") if o.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_default_origins + _extra_origins,
    # Vercel assigns immutable *.vercel.app URLs per deploy; regex covers
    # both the canonical alias (prism-y4shagarwal-3895s-projects) and per-
    # deploy hashes (prism-<sha>-y4shagarwal-3895s-projects).
    allow_origin_regex=r"https://prism(-[a-z0-9]+)?-y4shagarwal-3895s-projects\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount routers
app.include_router(projects.router)
app.include_router(screens.router)
app.include_router(edges.router)
app.include_router(plans.router)
app.include_router(knowledge.router)
app.include_router(product_os.router)
app.include_router(cost.router)
app.include_router(digest.router)
app.include_router(xproj.router)
app.include_router(prd.router)
app.include_router(reports.router)


@app.on_event("startup")
def on_startup() -> None:
    init_db()
    log = logging.getLogger(__name__)
    log.info("Prism API started — DB initialized")

    # v0.20.0: orphan reaper. Any work_item still in_progress on startup is
    # by definition orphaned — the process that owned it has died (either a
    # graceful redeploy or a crash). Without this, those rows sit in_progress
    # forever, the daemon's session lock prevents re-runs, and the user sees
    # a phantom "1 item running" badge for days. We mark them failed with a
    # clear summary so they don't pollute the running-count and so the agent
    # can pick them up again on the next generate_next_work() pass.
    from datetime import datetime, timedelta
    from webapp.api.db import SessionLocal as _SL
    from webapp.api.models import WorkItem as _WI, AgentSession as _AS
    _db = _SL()
    try:
        cutoff = datetime.utcnow() - timedelta(minutes=10)
        orphans = (
            _db.query(_WI)
            .filter(_WI.status == "in_progress")
            .filter((_WI.started_at == None) | (_WI.started_at < cutoff))  # noqa: E711
            .all()
        )
        for w in orphans:
            w.status = "failed"
            w.result_summary = (w.result_summary or "")[:200] + (
                " | Orphaned (no active session at startup; reaped)"
            )
            w.completed_at = datetime.utcnow()
        # Sessions stuck without completed_at older than 1h are also dead.
        stale_cutoff = datetime.utcnow() - timedelta(hours=1)
        stale_sessions = (
            _db.query(_AS)
            .filter(_AS.completed_at == None)  # noqa: E711
            .filter(_AS.started_at < stale_cutoff)
            .all()
        )
        for s in stale_sessions:
            s.completed_at = datetime.utcnow()
            s.session_summary = (s.session_summary or "") + " | Reaped at startup."
        _db.commit()
        if orphans or stale_sessions:
            log.info(
                "[startup-reaper] reaped %d orphaned work_items and %d stale sessions",
                len(orphans), len(stale_sessions),
            )
    except Exception as exc:
        log.error("[startup-reaper] failed: %s", exc, exc_info=True)
        _db.rollback()
    finally:
        _db.close()

    # Auto-start the research orchestrator daemon per project, for production
    # deploys (Railway). Gated behind PRISM_AUTO_DAEMON=1 so local `uvicorn
    # --reload` cycles don't spam provider APIs on every restart.
    import os
    if os.environ.get("PRISM_AUTO_DAEMON", "").strip() in ("1", "true", "yes"):
        from webapp.api.db import SessionLocal
        from webapp.api.models import Project
        from agent.product_os_orchestrator import ProductOSOrchestrator

        db = SessionLocal()
        try:
            projects = db.query(Project).all()
            for p in projects:
                try:
                    ProductOSOrchestrator(project_id=p.id).start_daemon()
                    log.info(
                        "[auto-daemon] started orchestrator for project %d (%s)",
                        p.id, p.name,
                    )
                except Exception as exc:
                    log.error(
                        "[auto-daemon] failed to start for project %d: %s",
                        p.id, exc, exc_info=True,
                    )
        finally:
            db.close()


@app.get("/api/health")
def health() -> dict:
    return {"status": "ok"}
