"""
agent/report_writer_agent.py — UAT report assembly subagent

Assembles the final UAT report from all subagent outputs.
Produces a structured, evidence-backed Markdown report.

Input: run_summary + evaluation_results + diff_analysis + variant_groups
Output: Markdown report saved to reports/uat_report_{run_id}.md
"""
from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path

from utils.claude_client import ask

logger = logging.getLogger(__name__)

_EXEC_SUMMARY_SYSTEM = (
    "You are a senior QA manager writing an executive summary for a UAT report. "
    "Be concise, factual, and professional. Respond with plain text only — "
    "no JSON, no markdown headings, no bullet points. Two to three sentences maximum."
)

_EXEC_SUMMARY_PROMPT = """\
Write a 2-3 sentence executive summary for a UAT report with the following data:

Feature: {feature}
Overall verdict: {overall_verdict}
Total scenarios: {total_scenarios}
Passed: {passed}
Failed: {failed}
Partial: {partial}
Variant differences: {variant_differences}
Critical failures: {critical_failures}
Build comparison summary: {diff_summary}

Write a clear, direct summary suitable for a product manager or tech lead.
State the verdict, highlight the most important findings, and give a recommendation.
"""

_DEFECT_DESCRIPTION_SYSTEM = (
    "You are a QA engineer writing a precise defect description for a bug report. "
    "Be factual and specific. Respond with plain text only — no JSON, no markdown, "
    "no headers. Three sentences maximum."
)

_DEFECT_DESCRIPTION_PROMPT = """\
Write a concise defect description for the following issue:

Scenario: {scenario_name}
Account affected: {account_id}
Issue observed: {description}
Steps to reproduce: {steps_to_reproduce}

Write a clear, actionable defect description suitable for a Jira bug report.
"""


class ReportWriterAgent:
    """
    Assembles the final UAT Markdown report from all subagent outputs.

    Only the executive summary and individual defect descriptions are
    generated by Claude — all structured sections are hand-assembled
    for reliability and consistency.
    """

    def __init__(self, run_id: str, reports_dir: str = "reports"):
        self.run_id = run_id
        self.reports_dir = reports_dir
        Path(reports_dir).mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def write_report(
        self,
        run_summary: dict,
        evaluation: dict,
        diff_analysis: dict,
        variant_groups: dict,
    ) -> str:
        """
        Assemble and save the full UAT Markdown report.

        Returns the path to the saved report file.
        """
        logger.info(f"[ReportWriterAgent] Assembling report for run_id={self.run_id}")

        # Extract key values used throughout
        feature = run_summary.get("feature", "Unknown Feature")
        run_date = datetime.now().strftime("%Y-%m-%d %H:%M")
        baseline_version = self._get_version(run_summary, "baseline")
        candidate_version = self._get_version(run_summary, "candidate")
        overall_verdict = evaluation.get("overall_verdict", "UNKNOWN")
        diff_summary = diff_analysis.get("summary", "No build comparison performed.")

        # --- Generate Claude-powered sections ---
        exec_summary = self._generate_exec_summary(feature, evaluation, diff_summary)

        # --- Assemble each section ---
        sections: list[str] = []

        sections.append(self._render_header(
            feature, run_date, baseline_version, candidate_version
        ))
        sections.append(self._render_exec_summary(exec_summary, overall_verdict, evaluation))
        sections.append(self._render_variant_analysis(variant_groups, evaluation))
        sections.append(self._render_build_comparison(diff_analysis))
        sections.append(self._render_scenario_results(evaluation))
        sections.append(self._render_defects(evaluation))
        sections.append(self._render_recommendations(evaluation, diff_analysis))

        report_content = "\n\n".join(sections)

        # Save to file
        report_path = os.path.join(self.reports_dir, f"uat_report_{self.run_id}.md")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_content)

        logger.info(f"[ReportWriterAgent] Report saved: {report_path}")
        return report_path

    # ------------------------------------------------------------------
    # Section renderers
    # ------------------------------------------------------------------

    def _render_header(
        self,
        feature: str,
        run_date: str,
        baseline_version: str,
        candidate_version: str,
    ) -> str:
        return (
            f"# UAT Report — {feature}\n\n"
            f"**Run ID:** {self.run_id}  \n"
            f"**Date:** {run_date}  \n"
            f"**Builds:** Baseline {baseline_version} vs Candidate {candidate_version}  \n"
            f"**Platform:** Android  \n"
            f"**Mode:** Autonomous  "
        )

    def _render_exec_summary(
        self,
        exec_summary: str,
        overall_verdict: str,
        evaluation: dict,
    ) -> str:
        verdict_badge = self._verdict_badge(overall_verdict)

        metric_rows = [
            ("Scenarios Tested", evaluation.get("total_scenarios", 0)),
            ("Passed", evaluation.get("passed", 0)),
            ("Failed", evaluation.get("failed", 0)),
            ("Partial", evaluation.get("partial", 0)),
            ("Variant Differences", evaluation.get("variant_differences", 0)),
            ("Blocked", evaluation.get("blocked", 0)),
            ("Critical Issues", evaluation.get("critical_failures", 0)),
        ]

        table_rows = "\n".join(f"| {m} | {c} |" for m, c in metric_rows)

        return (
            f"---\n\n"
            f"## Executive Summary\n\n"
            f"{exec_summary}\n\n"
            f"**Verdict: {verdict_badge}**\n\n"
            f"| Metric | Count |\n"
            f"|--------|-------|\n"
            f"{table_rows}"
        )

    def _render_variant_analysis(
        self,
        variant_groups: dict,
        evaluation: dict,
    ) -> str:
        lines: list[str] = ["---\n\n## Variant Analysis\n"]

        if not variant_groups:
            lines.append("No variant group data available for this run.")
            return "\n".join(lines)

        for label, accounts in variant_groups.items():
            lines.append(f"- **{label}**: accounts {', '.join(accounts)}")

        # Summarise any VARIANT_DIFFERENCE scenarios
        variant_scenarios = [
            e for e in evaluation.get("scenario_evaluations", [])
            if e.get("verdict") == "VARIANT_DIFFERENCE"
        ]
        if variant_scenarios:
            lines.append("")
            lines.append("**Scenarios where variant differences were observed:**")
            for e in variant_scenarios:
                lines.append(f"- {e['scenario_name']}: {e.get('variant_analysis', '')}")

        return "\n".join(lines)

    def _render_build_comparison(self, diff_analysis: dict) -> str:
        lines: list[str] = ["---\n\n## Build Comparison\n"]

        if not diff_analysis or not diff_analysis.get("comparisons"):
            lines.append("No build comparison data available.")
            return "\n".join(lines)

        lines.append(f"{diff_analysis.get('summary', '')}\n")
        lines.append(
            "| Screen | Change Type | Severity | Description |\n"
            "|--------|-------------|----------|-------------|"
        )

        for comp in diff_analysis.get("comparisons", []):
            screen = comp.get("screen_label", "unknown")
            change_type = comp.get("change_type", "UNKNOWN")
            severity = comp.get("severity", "none")
            description = comp.get("claude_analysis", "").replace("|", "\\|")[:100]
            lines.append(f"| {screen} | {change_type} | {severity} | {description} |")

        return "\n".join(lines)

    def _render_scenario_results(self, evaluation: dict) -> str:
        lines: list[str] = ["---\n\n## Scenario Results\n"]

        evals = evaluation.get("scenario_evaluations", [])
        if not evals:
            lines.append("No scenario evaluations available.")
            return "\n".join(lines)

        lines.append(
            "| Scenario | Category | Verdict | Severity | Notes |\n"
            "|----------|----------|---------|----------|-------|"
        )

        for e in evals:
            scenario_name = e.get("scenario_name", "Unknown").replace("|", "\\|")
            # We don't store category in the evaluation result, so leave blank
            category = "—"
            verdict = e.get("verdict", "UNKNOWN")
            verdict_icon = self._verdict_icon(verdict)
            severity = "—"
            notes = e.get("summary", "").replace("|", "\\|")[:80]
            lines.append(
                f"| {scenario_name} | {category} | {verdict_icon} {verdict} | {severity} | {notes} |"
            )

        return "\n".join(lines)

    def _render_defects(self, evaluation: dict) -> str:
        lines: list[str] = ["---\n\n## Defects\n"]

        all_defects: list[tuple[str, dict]] = []
        for e in evaluation.get("scenario_evaluations", []):
            if e.get("verdict") in ("FAIL", "PARTIAL"):
                for defect in e.get("defects", []):
                    all_defects.append((e["scenario_name"], defect))

        if not all_defects:
            lines.append("No defects found.")
            return "\n".join(lines)

        for scenario_name, defect in all_defects:
            severity = defect.get("severity", "medium").upper()
            account_id = defect.get("account_id", "unknown")
            description = defect.get("description", "No description.")
            steps = defect.get("steps_to_reproduce", "Not available.")

            # Generate a concise defect description via Claude
            refined_desc = self._generate_defect_description(
                scenario_name, account_id, description, steps
            )

            # Use first 60 chars of description as title
            title = description[:60].rstrip() + ("..." if len(description) > 60 else "")

            lines.append(
                f"### [{severity}] {title}\n\n"
                f"**Scenario:** {scenario_name}  \n"
                f"**Accounts affected:** {account_id}  \n"
                f"**Steps to reproduce:** {steps}  \n"
                f"**Description:** {refined_desc}  \n"
            )

        return "\n".join(lines)

    def _render_recommendations(
        self,
        evaluation: dict,
        diff_analysis: dict,
    ) -> str:
        lines: list[str] = ["---\n\n## Recommendations\n"]

        recommendations: list[str] = []

        overall_verdict = evaluation.get("overall_verdict", "UNKNOWN")
        critical_failures = evaluation.get("critical_failures", 0)
        failed = evaluation.get("failed", 0)
        variant_diffs = evaluation.get("variant_differences", 0)

        if overall_verdict == "FAIL":
            recommendations.append(
                "**Block release.** Critical or widespread failures detected. "
                "Fix all critical defects before proceeding."
            )
        elif overall_verdict == "PASS_WITH_ISSUES":
            recommendations.append(
                "**Conditional release.** Non-critical issues found. "
                "Review failed scenarios with the engineering team."
            )
        else:
            recommendations.append(
                "**Clear to release.** All scenarios passed. No blocking defects found."
            )

        if critical_failures > 0:
            recommendations.append(
                f"Fix {critical_failures} critical defect(s) before any release."
            )

        if failed > 0:
            recommendations.append(
                f"Investigate and retest {failed} failing scenario(s)."
            )

        if variant_diffs > 0:
            recommendations.append(
                f"Clarify with design/product whether the {variant_diffs} "
                "variant difference(s) are intentional A/B experiment outcomes."
            )

        # Add regression candidates from diff analysis
        regression_screens = [
            c["screen_label"]
            for c in diff_analysis.get("comparisons", [])
            if c.get("change_type") == "REGRESSION_CANDIDATE"
        ]
        if regression_screens:
            screens_str = ", ".join(regression_screens[:5])
            recommendations.append(
                f"Review regression candidate screens from build comparison: {screens_str}."
            )

        for rec in recommendations:
            lines.append(f"- {rec}")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Claude-generated content
    # ------------------------------------------------------------------

    def _generate_exec_summary(
        self,
        feature: str,
        evaluation: dict,
        diff_summary: str,
    ) -> str:
        """Ask Claude to write the executive summary narrative."""
        prompt = _EXEC_SUMMARY_PROMPT.format(
            feature=feature,
            overall_verdict=evaluation.get("overall_verdict", "UNKNOWN"),
            total_scenarios=evaluation.get("total_scenarios", 0),
            passed=evaluation.get("passed", 0),
            failed=evaluation.get("failed", 0),
            partial=evaluation.get("partial", 0),
            variant_differences=evaluation.get("variant_differences", 0),
            critical_failures=evaluation.get("critical_failures", 0),
            diff_summary=diff_summary,
        )

        try:
            return ask(prompt, system=_EXEC_SUMMARY_SYSTEM, max_tokens=256).strip()
        except Exception as e:
            logger.warning(f"[ReportWriterAgent] Executive summary generation failed: {e}")
            verdict = evaluation.get("overall_verdict", "UNKNOWN")
            return (
                f"UAT run completed with overall verdict: {verdict}. "
                f"{evaluation.get('passed', 0)} of {evaluation.get('total_scenarios', 0)} "
                f"scenarios passed. Review the detailed findings below."
            )

    def _generate_defect_description(
        self,
        scenario_name: str,
        account_id: str,
        description: str,
        steps_to_reproduce: str,
    ) -> str:
        """Ask Claude to write a polished defect description."""
        prompt = _DEFECT_DESCRIPTION_PROMPT.format(
            scenario_name=scenario_name,
            account_id=account_id,
            description=description,
            steps_to_reproduce=steps_to_reproduce,
        )

        try:
            return ask(prompt, system=_DEFECT_DESCRIPTION_SYSTEM, max_tokens=200).strip()
        except Exception as e:
            logger.warning(f"[ReportWriterAgent] Defect description generation failed: {e}")
            return description

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _get_version(run_summary: dict, build: str) -> str:
        """Extract version string from run_summary for 'baseline' or 'candidate'."""
        if build == "candidate":
            apk_version = run_summary.get("apk_version", {})
            name = apk_version.get("version_name", "?")
            code = apk_version.get("version_code", "?")
            return f"v{name} ({code})"
        else:
            # Baseline version not always available
            baseline_apk = run_summary.get("baseline_apk")
            if baseline_apk:
                return str(Path(baseline_apk).stem)
            return "N/A"

    @staticmethod
    def _verdict_badge(verdict: str) -> str:
        mapping = {
            "PASS": "PASS",
            "FAIL": "FAIL",
            "PASS_WITH_ISSUES": "PASS WITH ISSUES",
        }
        return mapping.get(verdict, verdict)

    @staticmethod
    def _verdict_icon(verdict: str) -> str:
        mapping = {
            "PASS": "✓",
            "FAIL": "✗",
            "PARTIAL": "~",
            "VARIANT_DIFFERENCE": "≠",
            "BLOCKED": "⊘",
        }
        return mapping.get(verdict, "?")
