"""
tools/report_generator.py — Report serialization

Converts the assembled Markdown report into additional formats:
- Jira-ready defect list (one dict per defect, ready for createJiraIssue)
- Slack summary (short text block)
- JSON export of full results
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

# Map severity strings to Jira priority labels
_SEVERITY_TO_JIRA_PRIORITY = {
    "critical": "Critical",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
}


def save_markdown(
    content: str,
    run_id: str,
    reports_dir: str = "reports",
) -> str:
    """
    Save Markdown report content to disk.

    Args:
        content:     The full Markdown report string.
        run_id:      Unique identifier for this UAT run.
        reports_dir: Directory to write the file into.

    Returns:
        Absolute path to the saved file.
    """
    Path(reports_dir).mkdir(parents=True, exist_ok=True)
    report_path = os.path.join(reports_dir, f"uat_report_{run_id}.md")

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info(f"[report_generator] Markdown report saved: {report_path}")
    return report_path


def to_jira_issues(evaluation: dict, run_id: str) -> list[dict]:
    """
    Convert FAIL defects in the evaluation to Jira issue dicts.

    Only FAIL (and PARTIAL) verdicts produce Jira issues.
    Each defect within a failing scenario becomes one Jira issue.

    Args:
        evaluation: Output of EvaluatorAgent.evaluate_run().
        run_id:     UAT run identifier, added to each issue as a label.

    Returns:
        List of Jira issue dicts ready for createJiraIssue.
    """
    issues: list[dict] = []

    for scenario_eval in evaluation.get("scenario_evaluations", []):
        verdict = scenario_eval.get("verdict", "")
        if verdict not in ("FAIL", "PARTIAL"):
            continue

        scenario_name = scenario_eval.get("scenario_name", "Unknown Scenario")

        for defect in scenario_eval.get("defects", []):
            account_id = defect.get("account_id", "unknown")
            description = defect.get("description", "No description provided.")
            severity = defect.get("severity", "medium").lower()
            steps = defect.get("steps_to_reproduce", "Not available.")

            priority = _SEVERITY_TO_JIRA_PRIORITY.get(severity, "Medium")

            # Build a full description string for the Jira issue body
            jira_description = (
                f"*UAT Run:* {run_id}\n\n"
                f"*Scenario:* {scenario_name}\n\n"
                f"*Account affected:* {account_id}\n\n"
                f"*Description:*\n{description}\n\n"
                f"*Steps to reproduce:*\n{steps}\n\n"
                f"_Auto-generated by MMT-OS autonomous UAT agent._"
            )

            issues.append({
                "summary": f"UAT Defect: {scenario_name} — {description[:80]}",
                "description": jira_description,
                "issue_type": "Bug",
                "priority": priority,
                "labels": ["UAT", "automated-test", "Product-OS"],
                "run_id": run_id,
            })

    logger.info(f"[report_generator] Generated {len(issues)} Jira issue(s) from evaluation")
    return issues


def to_slack_summary(
    evaluation: dict,
    run_id: str,
    report_path: str,
) -> str:
    """
    Build a Slack-formatted plain-text summary block.

    Args:
        evaluation:  Output of EvaluatorAgent.evaluate_run().
        run_id:      UAT run identifier.
        report_path: Path to the saved Markdown report.

    Returns:
        A plain text string suitable for a Slack message.
    """
    overall_verdict = evaluation.get("overall_verdict", "UNKNOWN")
    total = evaluation.get("total_scenarios", 0)
    passed = evaluation.get("passed", 0)
    failed = evaluation.get("failed", 0)
    variant_diffs = evaluation.get("variant_differences", 0)
    blocked = evaluation.get("blocked", 0)
    critical = evaluation.get("critical_failures", 0)

    # Pull feature name from the first scenario evaluation if available
    scenario_evals = evaluation.get("scenario_evaluations", [])
    feature_name = "Unknown Feature"

    lines = [
        f"UAT Run Complete: {feature_name}",
        f"Verdict: {overall_verdict} | Run: {run_id}",
        f"✓ Passed: {passed}  ✗ Failed: {failed}  ⚠ Variant: {variant_diffs}  ⊘ Blocked: {blocked}",
        f"Critical issues: {critical}",
        f"Report: {report_path}",
    ]

    return "\n".join(lines)


def save_json_export(
    run_summary: dict,
    evaluation: dict,
    diff_analysis: dict,
    run_id: str,
    reports_dir: str = "reports",
) -> str:
    """
    Save a combined JSON export of all run data.

    Args:
        run_summary:   Output of Orchestrator.run().
        evaluation:    Output of EvaluatorAgent.evaluate_run().
        diff_analysis: Output of DiffAgent.analyze() (or empty dict if no diff run).
        run_id:        UAT run identifier.
        reports_dir:   Directory to write the file into.

    Returns:
        Path to the saved JSON file.
    """
    Path(reports_dir).mkdir(parents=True, exist_ok=True)
    export_path = os.path.join(reports_dir, f"run_export_{run_id}.json")

    export = {
        "run_id": run_id,
        "exported_at": datetime.now().isoformat(),
        "run_summary": run_summary,
        "evaluation": evaluation,
        "diff_analysis": diff_analysis,
    }

    with open(export_path, "w", encoding="utf-8") as f:
        json.dump(export, f, indent=2)

    logger.info(f"[report_generator] JSON export saved: {export_path}")
    return export_path
